### PR TITLE
Add Chapter II: Introduction

### PR DESCRIPTION
**Pull request by GregCTWang**
Upload of Chapter II TRADITIONAL MANDARIN translation version | 華文翻譯第二章「資訊技術與民主：日益擴大的鴻溝」上傳。

### CODE REVIEW

**Comment by taipeicityeth** [comment]
nice, looks great!

**Comment by TenzinYangtso** [comment]
Could you please let me know where I can upload the latest version? or just use the last one I send?

**Comment by taipeicityeth** [comment]
cc @GregCTWang

**Comment by TenzinYangtso** [comment]
[技術對民主的威脅.md](https://github.com/taipeicityeth/plurality-traditional-mandarin-translation/files/11950461/default.md)

this one is the last version.

**Comment by GregCTWang** [comment]
Hi Gisele, I'm documenting that we agreed that the content is the same from our discussion, with the only difference being the Traditional Mandarin chapter titles have been added. Thanks!

cc @taipeicityeth

**Comment by TenzinYangtso** [comment]
So you've actually checked the date of the version, right? The one from 7/4, and then you added it to the title. That's fine then! Thank you.

**Pull request merged**
